# ranch.py - 牧场生物数据库（萌宠属 + 禽鸟属）
# P1-1 · batch1

RANCH_CATALOG = [
    # ==================== 萌宠属（8种） ====================
    # id / name / icon / desc / rarity / price / feed_cost / personality / output_type / output_desc / growth_stages / elite / special
    {
        "id": "rabbit_white",
        "name": "小白兔",
        "icon": "🐰",
        "desc": "毛茸茸的温顺生物，繁殖很快",
        "rarity": 0,
        "price": 10,
        "feed_cost": 5,
        "personality": "乖巧",
        "output_type": "兔毛",
        "output_desc": "兔毛×1（乖巧+20%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "rabbit_cotton",
        "name": "棉花兔",
        "icon": "🐇",
        "desc": "蓬松如云，常被误认为云朵",
        "rarity": 0,
        "price": 15,
        "feed_cost": 8,
        "personality": "乖巧",
        "output_type": "兔绒",
        "output_desc": "兔绒×1（乖巧+20%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "frog_jump",
        "name": "跳跳蛙",
        "icon": "🐸",
        "desc": "爱跳来跳去，荷塘边的歌手",
        "rarity": 0,
        "price": 8,
        "feed_cost": 4,
        "personality": "活泼",
        "output_type": "蛙油",
        "output_desc": "蛙油×1（活泼+15%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "frog_gold",
        "name": "金蛙",
        "icon": "🐸",
        "desc": "通体金色，据说能招财",
        "rarity": 1,
        "price": 25,
        "feed_cost": 12,
        "personality": "幸运",
        "output_type": "金蛙油",
        "output_desc": "金蛙油×1（幸运+25%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "kitty_gray",
        "name": "小奶猫",
        "icon": "🐱",
        "desc": "灰毛蓝眼，叫声像撒娇",
        "rarity": 0,
        "price": 12,
        "feed_cost": 6,
        "personality": "乖巧",
        "output_type": "猫毛",
        "output_desc": "猫毛×1（乖巧+20%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "kitty_orange",
        "name": "橘猫",
        "icon": "🐈",
        "desc": "能吃能睡，胖嘟嘟很可爱",
        "rarity": 1,
        "price": 20,
        "feed_cost": 10,
        "personality": "懒惰",
        "output_type": "猫毛",
        "output_desc": "猫毛×2（懒惰-30%产量）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "pup_brown",
        "name": "小棕狗",
        "icon": "🐶",
        "desc": "忠诚护主，眼神清澈",
        "rarity": 0,
        "price": 15,
        "feed_cost": 8,
        "personality": "忠诚",
        "output_type": "狗毛",
        "output_desc": "狗毛×1（忠诚+15%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "pup_black",
        "name": "黑背犬",
        "icon": "🐕",
        "desc": "警觉性强，看家好手",
        "rarity": 1,
        "price": 30,
        "feed_cost": 15,
        "personality": "忠诚",
        "output_type": "犬牙",
        "output_desc": "犬牙×1（忠诚+25%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },

    # ==================== 禽鸟属（4种） ====================
    {
        "id": "chick_yellow",
        "name": "小黄鸡",
        "icon": "🐤",
        "desc": "叽叽喳喳，农场最热闹的声音",
        "rarity": 0,
        "price": 8,
        "feed_cost": 4,
        "personality": "活泼",
        "output_type": "鸡蛋",
        "output_desc": "鸡蛋×1（活泼+15%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "chick_white",
        "name": "白羽鸡",
        "icon": "🐔",
        "desc": "羽毛雪白，产蛋率高",
        "rarity": 0,
        "price": 12,
        "feed_cost": 6,
        "personality": "乖巧",
        "output_type": "鸡蛋",
        "output_desc": "鸡蛋×1（乖巧+20%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "duck_yellow",
        "name": "小黄鸭",
        "icon": "🐤",
        "desc": "嘎嘎叫，爱在水中嬉戏",
        "rarity": 0,
        "price": 10,
        "feed_cost": 5,
        "personality": "活泼",
        "output_type": "鸭蛋",
        "output_desc": "鸭蛋×1（活泼+15%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "goose_white",
        "name": "白鹅",
        "icon": "🦢",
        "desc": "优雅高傲，看护领地意识强",
        "rarity": 1,
        "price": 25,
        "feed_cost": 12,
        "personality": "高傲",
        "output_type": "鹅绒",
        "output_desc": "鹅绒×1（高傲+20%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },

    # ==================== 禽鸟属（后4种） ====================
    {
        "id": "parrot_green",
        "name": "绿鹦鹉",
        "icon": "🦜",
        "desc": "会学舌，学什么像什么",
        "rarity": 1,
        "price": 30,
        "feed_cost": 15,
        "personality": "活泼",
        "output_type": "羽毛",
        "output_desc": "羽毛×1（活泼+15%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "owl_gray",
        "name": "灰林鸮",
        "icon": "🦉",
        "desc": "夜行智者，眼神深邃",
        "rarity": 1,
        "price": 35,
        "feed_cost": 18,
        "personality": "睿智",
        "output_type": "鸮羽",
        "output_desc": "鸮羽×1（睿智+20%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "phoenix_chick",
        "name": "雏凤",
        "icon": "🔥",
        "desc": "凤凰幼崽，羽尖带火星",
        "rarity": 2,
        "price": 80,
        "feed_cost": 40,
        "personality": "高傲",
        "output_type": "凤羽",
        "output_desc": "凤羽×1（高傲+25%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "crane_white",
        "name": "白鹤",
        "icon": "🦢",
        "desc": "仙风道骨，超然物外",
        "rarity": 2,
        "price": 100,
        "feed_cost": 50,
        "personality": "睿智",
        "output_type": "鹤羽",
        "output_desc": "鹤羽×1（睿智+25%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },

    # ==================== 异兽属（8种） ====================
    {
        "id": "slime_blue",
        "name": "史莱姆",
        "icon": "🟦",
        "desc": "软乎乎弹来弹去，最适合新手",
        "rarity": 0,
        "price": 10,
        "feed_cost": 5,
        "personality": "乖巧",
        "output_type": "凝胶",
        "output_desc": "凝胶×1（乖巧+20%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "slime_gold",
        "name": "金史莱姆",
        "icon": "🟨",
        "desc": "闪闪发光，内含稀有矿物质",
        "rarity": 1,
        "price": 30,
        "feed_cost": 15,
        "personality": "幸运",
        "output_type": "黄金凝胶",
        "output_desc": "黄金凝胶×1（幸运+25%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "slime_dark",
        "name": "暗影史莱姆",
        "icon": "🟪",
        "desc": "藏匿于暗处，很少现身",
        "rarity": 1,
        "price": 35,
        "feed_cost": 18,
        "personality": "暴躁",
        "output_type": "暗凝胶",
        "output_desc": "暗凝胶×1（暴躁+30%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "bat_flying",
        "name": "飞蝠",
        "icon": "🦇",
        "desc": "倒挂金钩，夜晚最活跃",
        "rarity": 0,
        "price": 12,
        "feed_cost": 6,
        "personality": "暴躁",
        "output_type": "翼膜",
        "output_desc": "翼膜×1（暴躁+30%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "turtle_green",
        "name": "小绿龟",
        "icon": "🐢",
        "desc": "慢悠悠，寿命极长",
        "rarity": 0,
        "price": 15,
        "feed_cost": 8,
        "personality": "睿智",
        "output_type": "龟壳",
        "output_desc": "龟壳×1（睿智+20%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "turtle_gold",
        "name": "金甲龟",
        "icon": "🐢",
        "desc": "龟壳如金，防御惊人",
        "rarity": 2,
        "price": 60,
        "feed_cost": 30,
        "personality": "忠诚",
        "output_type": "金龟壳",
        "output_desc": "金龟壳×1（忠诚+25%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "fox_white",
        "name": "白灵狐",
        "icon": "🦊",
        "desc": "九条尾巴的传说（还剩1条）",
        "rarity": 2,
        "price": 90,
        "feed_cost": 45,
        "personality": "幸运",
        "output_type": "狐尾",
        "output_desc": "狐尾×1（幸运+25%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },
    {
        "id": "fox_red",
        "name": "赤焰狐",
        "icon": "🔥",
        "desc": "皮毛如燃烧的火焰",
        "rarity": 2,
        "price": 100,
        "feed_cost": 50,
        "personality": "暴躁",
        "output_type": "火狐毛",
        "output_desc": "火狐毛×1（暴躁+30%）",
        "growth_stages": [],
        "elite": False,
        "special": "",
    },

    # ==================== 兽王属（8种） ====================
    {
        "id": "lion_king",
        "name": "狮王",
        "icon": "🦁",
        "desc": "百兽之王，威严不可侵犯",
        "rarity": 2,
        "price": 120,
        "feed_cost": 60,
        "personality": "高傲",
        "output_type": "王鬃",
        "output_desc": "王鬃×1（高傲+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "tiger_stripe",
        "name": "猛虎",
        "icon": "🐯",
        "desc": "斑纹如画，力量与敏捷并存",
        "rarity": 2,
        "price": 110,
        "feed_cost": 55,
        "personality": "暴躁",
        "output_type": "虎骨",
        "output_desc": "虎骨×1（暴躁+30%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "bear_brown",
        "name": "棕熊",
        "icon": "🐻",
        "desc": "力大无穷，憨态可掬",
        "rarity": 2,
        "price": 100,
        "feed_cost": 50,
        "personality": "忠诚",
        "output_type": "熊胆",
        "output_desc": "熊胆×1（忠诚+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "wolf_silver",
        "name": "银狼",
        "icon": "🐺",
        "desc": "银毛如月，团队狩猎的领袖",
        "rarity": 2,
        "price": 105,
        "feed_cost": 52,
        "personality": "睿智",
        "output_type": "狼牙",
        "output_desc": "狼牙×1（睿智+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "panther_black",
        "name": "黑豹",
        "icon": "🐆",
        "desc": "黑如暗夜，行动悄无声息",
        "rarity": 2,
        "price": 115,
        "feed_cost": 58,
        "personality": "暴躁",
        "output_type": "黑豹皮",
        "output_desc": "黑豹皮×1（暴躁+30%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "elephant_gray",
        "name": "巨象",
        "icon": "🐘",
        "desc": "庞然大物，记忆力惊人",
        "rarity": 3,
        "price": 150,
        "feed_cost": 75,
        "personality": "睿智",
        "output_type": "象牙",
        "output_desc": "象牙×1（睿智+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "rhino_gray",
        "name": "犀牛",
        "icon": "🦏",
        "desc": "皮坚甲厚，正面冲锋无惧",
        "rarity": 3,
        "price": 140,
        "feed_cost": 70,
        "personality": "忠诚",
        "output_type": "犀角",
        "output_desc": "犀角×1（忠诚+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "bear_panda",
        "name": "熊猫",
        "icon": "🐼",
        "desc": "黑白分明，国宝级萌兽",
        "rarity": 3,
        "price": 200,
        "feed_cost": 100,
        "personality": "乖巧",
        "output_type": "竹心",
        "output_desc": "竹心×1（乖巧+20%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },

    # ==================== 仙灵属（4种） ====================
    {
        "id": "fairy_elf",
        "name": "森林精灵",
        "icon": "🧚",
        "desc": "与自然共鸣，身形轻盈如风",
        "rarity": 2,
        "price": 90,
        "feed_cost": 45,
        "personality": "睿智",
        "output_type": "精灵粉",
        "output_desc": "精灵粉×1（睿智+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "fairy_angel",
        "name": "天使",
        "icon": "👼",
        "desc": "羽翼洁白，治愈之力温和",
        "rarity": 3,
        "price": 180,
        "feed_cost": 90,
        "personality": "乖巧",
        "output_type": "圣羽",
        "output_desc": "圣羽×1（乖巧+20%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "fairy_demon",
        "name": "恶魔",
        "icon": "😈",
        "desc": "暗红双翼，力量与危险并存",
        "rarity": 3,
        "price": 160,
        "feed_cost": 80,
        "personality": "暴躁",
        "output_type": "魔角",
        "output_desc": "魔角×1（暴躁+30%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },
    {
        "id": "fairy_dragon",
        "name": "幼龙",
        "icon": "🐉",
        "desc": "龙族幼崽，潜力无限的传说生物",
        "rarity": 3,
        "price": 250,
        "feed_cost": 125,
        "personality": "高傲",
        "output_type": "龙鳞",
        "output_desc": "龙鳞×1（高傲+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "",
    },

    # ==================== 精英异化属（7种） ====================
    {
        "id": "slime_prism",
        "name": "棱晶史莱姆",
        "icon": "💎",
        "desc": "体内结晶化，产出高纯度凝胶",
        "rarity": 3,
        "price": 200,
        "feed_cost": 100,
        "personality": "睿智",
        "output_type": "棱晶凝胶",
        "output_desc": "棱晶凝胶×1（睿智+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "棱晶化",
    },
    {
        "id": "phoenix_elite",
        "name": "凤皇",
        "icon": "🔥",
        "desc": "浴火重生，九次涅槃",
        "rarity": 4,
        "price": 800,
        "feed_cost": 400,
        "personality": "高傲",
        "output_type": "凤羽×2",
        "output_desc": "凤羽×2（高傲+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "涅槃",
    },
    {
        "id": "dragon_golden",
        "name": "金龙",
        "icon": "🌟",
        "desc": "鳞片如黄金，至高神兽",
        "rarity": 4,
        "price": 1000,
        "feed_cost": 500,
        "personality": "幸运",
        "output_type": "龙鳞×2",
        "output_desc": "龙鳞×2（幸运+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "金龙血",
    },
    {
        "id": "qilin_celestial",
        "name": "祥瑞麒麟",
        "icon": "✨",
        "desc": "天降祥瑞，草木逢春",
        "rarity": 4,
        "price": 1200,
        "feed_cost": 600,
        "personality": "幸运",
        "output_type": "麒麟鳞×2",
        "output_desc": "麒麟鳞×2（幸运+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "祥瑞",
    },
    {
        "id": "unicorn_celestial",
        "name": "星辉独角兽",
        "icon": "⭐",
        "desc": "角含星河，触碰即发光",
        "rarity": 4,
        "price": 1000,
        "feed_cost": 500,
        "personality": "高傲",
        "output_type": "独角毛×2",
        "output_desc": "独角毛×2（高傲+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "星辉",
    },
    {
        "id": "bunny_lunar",
        "name": "月兔",
        "icon": "🌙",
        "desc": "居住于月中，玉兔捣药",
        "rarity": 4,
        "price": 800,
        "feed_cost": 400,
        "personality": "睿智",
        "output_type": "月兔毛",
        "output_desc": "月兔毛×1（睿智+25%）",
        "growth_stages": [],
        "elite": True,
        "special": "月兔捣药",
    },
    {
        "id": "wolf_moonfang",
        "name": "月牙狼",
        "icon": "🌕",
        "desc": "传说中月圆之夜的化身",
        "rarity": 4,
        "price": 900,
        "feed_cost": 450,
        "personality": "暴躁",
        "output_type": "月牙牙",
        "output_desc": "月牙牙×1（暴躁+30%）",
        "growth_stages": [],
        "elite": True,
        "special": "月牙化",
    },
]
