# ranch.py - 牧场生物数据库（萌宠属 + 禽鸟属）
# P1-1 · batch1

RANCH_CATALOG = [
    # ==================== 萌宠属（8种） ====================
    # id / name / icon / desc / rarity / price / feed_cost / personality / output_type / output_desc / growth_stages / elite / special
    {
        "id": "rabbit_white",
        "name": "霜绒兔",
        "icon": "🐰",
        "desc": "霜白绒软，灵韵初生",
        "rarity": 0,
        "price": 10,
        "feed_cost": 5,
        "personality": "乖巧",
        "output_type": "兔毛",
        "output_desc": "兔毛×1（乖巧+20%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "rabbit_cotton",
        "name": "云绒兽",
        "icon": "🐇",
        "desc": "如云似绒，柔若无骨",
        "rarity": 0,
        "price": 15,
        "feed_cost": 8,
        "personality": "乖巧",
        "output_type": "兔绒",
        "output_desc": "兔绒×1（乖巧+20%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "frog_jump",
        "name": "碧蟾",
        "icon": "🐸",
        "desc": "碧色如玉，跳掷如簧",
        "rarity": 0,
        "price": 8,
        "feed_cost": 4,
        "personality": "活泼",
        "output_type": "蛙油",
        "output_desc": "蛙油×1（活泼+15%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "frog_gold",
        "name": "金蟾",
        "icon": "🐸",
        "desc": "金肌如玉，招财进宝",
        "rarity": 1,
        "price": 25,
        "feed_cost": 12,
        "personality": "幸运",
        "output_type": "金蟾油",
        "output_desc": "金蟾油×1（幸运+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "kitty_gray",
        "name": "玄猫",
        "icon": "🐱",
        "desc": "玄黑灵猫，目光幽邃",
        "rarity": 0,
        "price": 12,
        "feed_cost": 6,
        "personality": "乖巧",
        "output_type": "猫毛",
        "output_desc": "猫毛×1（乖巧+20%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "kitty_orange",
        "name": "赤狸",
        "icon": "🐈",
        "desc": "赤毛如火，灵动机敏",
        "rarity": 1,
        "price": 20,
        "feed_cost": 10,
        "personality": "懒惰",
        "output_type": "猫毛",
        "output_desc": "猫毛×2（懒惰-30%产量）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "pup_brown",
        "name": "玄犬",
        "icon": "🐶",
        "desc": "玄毛护主，忠诚无二",
        "rarity": 0,
        "price": 15,
        "feed_cost": 8,
        "personality": "忠诚",
        "output_type": "狗毛",
        "output_desc": "狗毛×1（忠诚+15%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "pup_black",
        "name": "玄卫犬",
        "icon": "🐕",
        "desc": "玄背护主，警觉如卫",
        "rarity": 1,
        "price": 30,
        "feed_cost": 15,
        "personality": "忠诚",
        "output_type": "犬牙",
        "output_desc": "犬牙×1（忠诚+25%）",
        "growth_stages": [],
        "special": "",
    },

    # ==================== 禽鸟属（4种） ====================
    {
        "id": "chick_yellow",
        "name": "赤凤",
        "icon": "🐤",
        "desc": "赤羽如火，凤仪初显",
        "rarity": 0,
        "price": 8,
        "feed_cost": 4,
        "personality": "活泼",
        "output_type": "鸡蛋",
        "output_desc": "鸡蛋×1（活泼+15%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "chick_white",
        "name": "素羽鸡",
        "icon": "🐔",
        "desc": "素羽如雪，清雅不凡",
        "rarity": 0,
        "price": 12,
        "feed_cost": 6,
        "personality": "乖巧",
        "output_type": "鸡蛋",
        "output_desc": "鸡蛋×1（乖巧+20%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "duck_yellow",
        "name": "黄绒鸭",
        "icon": "🐤",
        "desc": "绒黄似金，游弋悠然",
        "rarity": 0,
        "price": 10,
        "feed_cost": 5,
        "personality": "活泼",
        "output_type": "鸭蛋",
        "output_desc": "鸭蛋×1（活泼+15%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "goose_white",
        "name": "素羽鹅",
        "icon": "🦢",
        "desc": "素羽高洁，领地意识强",
        "rarity": 1,
        "price": 25,
        "feed_cost": 12,
        "personality": "高傲",
        "output_type": "鹅绒",
        "output_desc": "鹅绒×1（高傲+20%）",
        "growth_stages": [],
        "special": "",
    },

    # ==================== 禽鸟属（后4种） ====================
    {
        "id": "parrot_green",
        "name": "紫翼鹦鹉",
        "icon": "🦜",
        "desc": "紫翼绚丽，善学人言",
        "rarity": 1,
        "price": 30,
        "feed_cost": 15,
        "personality": "活泼",
        "output_type": "羽毛",
        "output_desc": "羽毛×1（活泼+15%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "owl_gray",
        "name": "灰羽鸮",
        "icon": "🦉",
        "desc": "灰羽静立，夜行智者",
        "rarity": 1,
        "price": 35,
        "feed_cost": 18,
        "personality": "睿智",
        "output_type": "鸮羽",
        "output_desc": "鸮羽×1（睿智+20%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "phoenix_chick",
        "name": "赤凤",
        "icon": "🔥",
        "desc": "赤羽如火，凤仪初显",
        "rarity": 2,
        "price": 80,
        "feed_cost": 40,
        "personality": "高傲",
        "output_type": "凤羽",
        "output_desc": "凤羽×1（高傲+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "crane_white",
        "name": "玄羽鹤",
        "icon": "🦢",
        "desc": "玄羽素雅，仙风道骨",
        "rarity": 2,
        "price": 100,
        "feed_cost": 50,
        "personality": "睿智",
        "output_type": "鹤羽",
        "output_desc": "鹤羽×1（睿智+25%）",
        "growth_stages": [],
        "special": "",
    },

    # ==================== 异兽属（8种） ====================
    {
        "id": "slime_blue",
        "name": "水精",
        "icon": "🟦",
        "desc": "凝水为形，灵动如溪",
        "rarity": 0,
        "price": 10,
        "feed_cost": 5,
        "personality": "乖巧",
        "output_type": "凝胶",
        "output_desc": "凝胶×1（乖巧+20%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "slime_gold",
        "name": "金髓",
        "icon": "🟨",
        "desc": "金色凝髓，价值不菲",
        "rarity": 1,
        "price": 30,
        "feed_cost": 15,
        "personality": "幸运",
        "output_type": "黄金凝胶",
        "output_desc": "黄金凝胶×1（幸运+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "slime_dark",
        "name": "暗髓",
        "icon": "🟪",
        "desc": "暗色凝聚，幽隐难测",
        "rarity": 1,
        "price": 35,
        "feed_cost": 18,
        "personality": "暴躁",
        "output_type": "暗凝胶",
        "output_desc": "暗凝胶×1（暴躁+30%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "bat_flying",
        "name": "夜蝠",
        "icon": "🦇",
        "desc": "隐于夜暮，悄然无声",
        "rarity": 0,
        "price": 12,
        "feed_cost": 6,
        "personality": "暴躁",
        "output_type": "翼膜",
        "output_desc": "翼膜×1（暴躁+30%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "turtle_green",
        "name": "翠甲龟",
        "icon": "🐢",
        "desc": "翠甲如玉，寿比南山",
        "rarity": 0,
        "price": 15,
        "feed_cost": 8,
        "personality": "睿智",
        "output_type": "龟壳",
        "output_desc": "龟壳×1（睿智+20%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "turtle_gold",
        "name": "金甲玄龟",
        "icon": "🐢",
        "desc": "金甲玄纹，坚不可摧",
        "rarity": 2,
        "price": 60,
        "feed_cost": 30,
        "personality": "忠诚",
        "output_type": "金龟壳",
        "output_desc": "金龟壳×1（忠诚+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "fox_white",
        "name": "九尾狐",
        "icon": "🦊",
        "desc": "九尾之狐，传说之灵",
        "rarity": 2,
        "price": 90,
        "feed_cost": 45,
        "personality": "幸运",
        "output_type": "狐尾",
        "output_desc": "狐尾×1（幸运+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "fox_red",
        "name": "赤焰妖狐",
        "icon": "🔥",
        "desc": "赤焰为毛，妖媚如火",
        "rarity": 2,
        "price": 100,
        "feed_cost": 50,
        "personality": "暴躁",
        "output_type": "火狐毛",
        "output_desc": "火狐毛×1（暴躁+30%）",
        "growth_stages": [],
        "special": "",
    },

    # ==================== 兽王属（8种） ====================
    {
        "id": "lion_king",
        "name": "鬃狮",
        "icon": "🦁",
        "desc": "鬃毛如王，百兽敬畏",
        "rarity": 2,
        "price": 120,
        "feed_cost": 60,
        "personality": "高傲",
        "output_type": "王鬃",
        "output_desc": "王鬃×1（高傲+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "tiger_stripe",
        "name": "斑斓虎",
        "icon": "🐯",
        "desc": "斑斓如画，力与敏捷",
        "rarity": 2,
        "price": 110,
        "feed_cost": 55,
        "personality": "暴躁",
        "output_type": "虎骨",
        "output_desc": "虎骨×1（暴躁+30%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "bear_brown",
        "name": "熊罴",
        "icon": "🐻",
        "desc": "体壮如罴，威猛憨厚",
        "rarity": 2,
        "price": 100,
        "feed_cost": 50,
        "personality": "忠诚",
        "output_type": "熊胆",
        "output_desc": "熊胆×1（忠诚+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "wolf_silver",
        "name": "霜银狼",
        "icon": "🐺",
        "desc": "银毛如霜，孤傲猎手",
        "rarity": 2,
        "price": 105,
        "feed_cost": 52,
        "personality": "睿智",
        "output_type": "狼牙",
        "output_desc": "狼牙×1（睿智+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "panther_black",
        "name": "玄影豹",
        "icon": "🐆",
        "desc": "黑如玄影，行动无踪",
        "rarity": 2,
        "price": 115,
        "feed_cost": 58,
        "personality": "暴躁",
        "output_type": "玄影豹皮",
        "output_desc": "玄影豹皮×1（暴躁+30%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "rhino_gray",
        "name": "犀牛",
        "icon": "🦏",
        "desc": "皮坚甲厚，正面冲锋无惧",
        "rarity": 3,
        "price": 140,
        "feed_cost": 70,
        "personality": "忠诚",
        "output_type": "犀角",
        "output_desc": "犀角×1（忠诚+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "bear_panda",
        "name": "玄墨",
        "icon": "🐼",
        "desc": "玄墨之色，灵韵内敛",
        "rarity": 3,
        "price": 200,
        "feed_cost": 100,
        "personality": "乖巧",
        "output_type": "竹心",
        "output_desc": "竹心×1（乖巧+20%）",
        "growth_stages": [],
        "special": "",
    },

    # ==================== 仙灵属（4种） ====================
    {
        "id": "fairy_elf",
        "name": "林灵",
        "icon": "🧚",
        "desc": "林间之灵，与自然共鸣",
        "rarity": 2,
        "price": 90,
        "feed_cost": 45,
        "personality": "睿智",
        "output_type": "精灵粉",
        "output_desc": "精灵粉×1（睿智+25%）",
        "growth_stages": [],
        "special": "",
    },
    {
        "id": "fairy_angel",
        "name": "天使",
        "icon": "👼",
        "desc": "羽翼洁白，治愈之力温和",
        "rarity": 3,
        "price": 180,
        "feed_cost": 90,
        "personality": "乖巧",
        "output_type": "圣羽",
        "output_desc": "圣羽×1（乖巧+20%）",
        "growth_stages": [],
        "special": "",
    },

        # ==================== 精英异化属（7种） ====================
    {
        "id": "chuiyun_oldman",
        "name": "垂云叟",
        "icon": "🧙",
        "desc": "隐居云端，长须垂落千年",
        "rarity": 4,
        "price": 220,
        "feed_cost": 110,
        "personality": "睿智",
        "output_type": "云须",
        "output_desc": "云须×1（睿智+25%）",
        "growth_stages": [],
        "special": "垂云",
    },
    {
        "id": "langtaosha",
        "name": "浪淘沙",
        "icon": "🌊",
        "desc": "浪涛中淘尽沙砾，力量磅礴",
        "rarity": 4,
        "price": 160,
        "feed_cost": 80,
        "personality": "暴躁",
        "output_type": "浪核",
        "output_desc": "浪核×1（暴躁+30%）",
        "growth_stages": [],
        "special": "淘沙",
    },
    {
        "id": "wuye",
        "name": "五叶",
        "icon": "🍀",
        "desc": "五叶灵草，世间罕见",
        "rarity": 3,
        "price": 180,
        "feed_cost": 90,
        "personality": "乖巧",
        "output_type": "灵叶",
        "output_desc": "灵叶×1（乖巧+20%）",
        "growth_stages": [],
        "special": "五叶",
    },
    {
        "id": "fanshizhihun",
        "name": "范式之魂",
        "icon": "🔥",
        "desc": "范式之魂，薪火相传不灭",
        "rarity": 4,
        "price": 250,
        "feed_cost": 125,
        "personality": "高傲",
        "output_type": "薪火",
        "output_desc": "薪火×1（高傲+25%）",
        "growth_stages": [],
        "special": "范式",
    },
    {
        "id": "yanruyu",
        "name": "颜如玉",
        "icon": "📖",
        "desc": "书中自有颜如玉，温文尔雅",
        "rarity": 4,
        "price": 170,
        "feed_cost": 85,
        "personality": "乖巧",
        "output_type": "书香",
        "output_desc": "书香×1（乖巧+20%）",
        "growth_stages": [],
        "special": "颜如玉",
    },
]

# END_RANCH_CATALOG
# END_RANCH_CATALOG
